use afrn_v5::{
    Result, data,
    model::{self, Model},
    proposal::Rng,
    train::{self, Budget, Options},
    vm::Limits,
};
use serde_json::json;
use std::{
    collections::{BTreeMap, BTreeSet},
    fs::{self, OpenOptions},
    io::Write,
    path::{Path, PathBuf},
    time::Instant,
};

const HELP: &str = "AFRN v5: bounded discrete program induction (experimental)

  cargo run --release -- train --input ../../data/train.jsonl --output ../experiment/v5.model
  cargo run --release -- train --resume ../experiment/v5.model --input ../../data/new.jsonl --output ../experiment/v5-next.model
  cargo run --release -- infer --model ../experiment/v5.model --prompt 'Once upon a time,' --n 200
  cargo run --release -- eval --model ../experiment/v5.model --input ../../data/test.jsonl --report ../experiment/test.json
  cargo run -- inspect --model ../experiment/v5.model

train: --validation PATH --report PATH --rounds 24 --candidates 16 --beam 4
       --max-experts 8 --feature-cap 512 --max-model-bytes 67108864
       --max-data-bytes 67108864 --max-work 500000000 --max-seconds 600
       --mdl-weight 0.02 --work-weight 0.000001 --seed 42 --replay-bytes 65536
       --observe-fuel 32768 --predict-fuel 32768 --prediction-budget 100000
       --memory-entries 2048 --memory-bytes 2097152 --max-value-bytes 4096
       --stop-on-bpb-increase (optional; restores prior committed model)
infer: --prompt TEXT or --prompt-file PATH --n 200 --temperature 0.85 --seed 42
       --output PATH (generated bytes only; otherwise stdout includes prompt)
       --budget N (prediction work budget; observation limits remain in model)
eval:  --budget N --report PATH
infer/eval: --max-data-bytes 67108864 --max-work 500000000 --max-seconds 600

Input: .jsonl with strings, {\"text\":...}, or {\"bytes\":[0,255,...]}; other
extensions are one raw binary document. No external tokenizer. All output files
must be new. Model v5 is incompatible with the previous suffix-tree model.
";

struct Args {
    values: BTreeMap<String, String>,
    flags: BTreeSet<String>,
}
impl Args {
    fn parse(words: &[String], values: &[&str], flags: &[&str]) -> Result<Self> {
        let mut a = Self {
            values: BTreeMap::new(),
            flags: BTreeSet::new(),
        };
        let mut i = 0;
        while i < words.len() {
            let k = words[i].strip_prefix("--").ok_or("expected --option")?;
            if a.values.contains_key(k) || a.flags.contains(k) {
                return Err(format!("duplicate --{k}").into());
            }
            if flags.contains(&k) {
                a.flags.insert(k.to_string());
                i += 1;
            } else if values.contains(&k) {
                let v = words.get(i + 1).ok_or("missing option value")?;
                if v.starts_with("--") {
                    return Err(format!("missing value for --{k}").into());
                }
                a.values.insert(k.to_string(), v.clone());
                i += 2;
            } else {
                return Err(format!("unknown --{k}").into());
            }
        }
        Ok(a)
    }
    fn required(&self, name: &str) -> Result<&str> {
        self.values
            .get(name)
            .map(String::as_str)
            .ok_or_else(|| format!("missing --{name}").into())
    }
    fn number<T: std::str::FromStr>(&self, name: &str, default: T) -> Result<T> {
        self.values.get(name).map_or(Ok(default), |s| {
            s.parse().map_err(|_| format!("invalid --{name}").into())
        })
    }
    fn path(&self, name: &str) -> Option<PathBuf> {
        self.values.get(name).map(PathBuf::from)
    }
}
fn new_output(path: &Path) -> Result<PathBuf> {
    if path.exists() || path.symlink_metadata().is_ok() {
        return Err(format!("refusing to overwrite {}", path.display()).into());
    }
    let parent = path
        .parent()
        .filter(|p| !p.as_os_str().is_empty())
        .unwrap_or(Path::new("."));
    Ok(parent
        .canonicalize()?
        .join(path.file_name().ok_or("output requires filename")?))
}
fn write_json(path: &Path, value: &impl serde::Serialize) -> Result<()> {
    let mut f = OpenOptions::new().write(true).create_new(true).open(path)?;
    serde_json::to_writer_pretty(&mut f, value)?;
    f.write_all(b"\n")?;
    Ok(())
}
fn data_limit(a: &Args) -> Result<usize> {
    let n = a.number("max-data-bytes", 64 * 1024 * 1024usize)?;
    if n == 0 || n > 2 * 1024 * 1024 * 1024usize {
        return Err("max-data-bytes must be 1..2GiB".into());
    }
    Ok(n)
}
fn run_train(words: &[String]) -> Result<()> {
    let a = Args::parse(
        words,
        &[
            "input",
            "validation",
            "output",
            "report",
            "resume",
            "rounds",
            "candidates",
            "beam",
            "max-experts",
            "max-model-bytes",
            "max-data-bytes",
            "max-work",
            "max-seconds",
            "mdl-weight",
            "work-weight",
            "seed",
            "replay-bytes",
            "feature-cap",
            "observe-fuel",
            "predict-fuel",
            "prediction-budget",
            "memory-entries",
            "memory-bytes",
            "max-value-bytes",
        ],
        &["stop-on-bpb-increase"],
    )?;
    let output = Path::new(a.required("output")?);
    let report_path = a
        .path("report")
        .unwrap_or_else(|| output.with_extension("report.json"));
    if new_output(output)? == new_output(&report_path)? {
        return Err("model and report need different paths".into());
    }
    let started = Instant::now();
    let cap = data_limit(&a)?;
    let docs = data::read(Path::new(a.required("input")?), cap)?;
    let validation = a
        .path("validation")
        .map(|p| data::read(&p, cap))
        .transpose()?;
    let split = data::split(docs, validation)?;
    let mut model = if let Some(path) = a.path("resume") {
        model::load(&path)?
    } else {
        Model::new(Limits::default(), 512)
    };
    let previous_limits = model.limits.clone();
    let previous_features = model.feature_cap;
    model.limits.observe_fuel = a.number("observe-fuel", model.limits.observe_fuel)?;
    model.limits.predict_fuel = a.number("predict-fuel", model.limits.predict_fuel)?;
    model.limits.memory_entries = a.number("memory-entries", model.limits.memory_entries)?;
    model.limits.memory_bytes = a.number("memory-bytes", model.limits.memory_bytes)?;
    model.limits.max_value_bytes = a.number("max-value-bytes", model.limits.max_value_bytes)?;
    model.feature_cap = a.number("feature-cap", model.feature_cap)?;
    model.prediction_budget = a.number("prediction-budget", model.prediction_budget)?;
    if a.values.contains_key("resume")
        && (previous_limits != model.limits || previous_features != model.feature_cap)
    {
        return Err(
            "resume must keep VM limits/feature-cap identical for deterministic evidence".into(),
        );
    }
    let mut opts = Options::default();
    opts.rounds = a.number("rounds", opts.rounds)?;
    opts.candidates_per_round = a.number("candidates", opts.candidates_per_round)?;
    opts.beam = a.number("beam", opts.beam)?;
    opts.max_experts = a.number("max-experts", opts.max_experts)?;
    opts.max_model_bytes = a.number("max-model-bytes", opts.max_model_bytes)?;
    opts.max_work = a.number("max-work", opts.max_work)?;
    opts.max_seconds = a.number("max-seconds", opts.max_seconds)?;
    opts.mdl_weight = a.number("mdl-weight", opts.mdl_weight)?;
    opts.work_weight = a.number("work-weight", opts.work_weight)?;
    opts.seed = a.number("seed", opts.seed)?;
    opts.replay_bytes = a.number("replay-bytes", opts.replay_bytes)?;
    opts.stop_on_bpb_increase = a.flags.contains("stop-on-bpb-increase");
    println!(
        "train={} bytes calibration={} bytes development={} bytes",
        data::byte_count(&split.train),
        data::byte_count(&split.calibration),
        data::byte_count(&split.development)
    );
    println!("round candidates experts modules model_bytes dev_bpb objective action seconds");
    let (model, report) = train::train(model, split, opts, |r| {
        println!(
            "{} {} {} {} {} {:.8} {:.8} {} {:.2}",
            r.round,
            r.candidates,
            r.experts,
            r.modules,
            r.model_bytes,
            r.development_bpb,
            r.objective,
            r.accepted,
            r.elapsed_seconds
        )
    })?;
    let size = model::save(output, &model)?;
    if model::load(output)? != model {
        return Err("model round-trip mismatch".into());
    }
    let report_json = json!({"training":report,"model_bytes":size,"command_seconds":started.elapsed().as_secs_f64(),
        "input":a.required("input")?,"validation":a.values.get("validation"),"resume":a.values.get("resume"),
        "saved_model":output,"process_usage":afrn_v5::resources::usage(),
        "memory_measurement":"VM accounted state includes scratch-register copies; OS peak RSS includes this process corpus/model/search allocations; work units are not CPU instructions"});
    write_json(&report_path, &report_json)?;
    println!(
        "saved {} ({} bytes); {}",
        output.display(),
        size,
        report_json["training"]["stop_reason"]
    );
    Ok(())
}
fn run_eval(words: &[String]) -> Result<()> {
    let a = Args::parse(
        words,
        &[
            "model",
            "input",
            "report",
            "budget",
            "max-data-bytes",
            "max-work",
            "max-seconds",
        ],
        &[],
    )?;
    if let Some(p) = a.path("report") {
        new_output(&p)?;
    }
    let model = model::load(Path::new(a.required("model")?))?;
    let docs = data::read(Path::new(a.required("input")?), data_limit(&a)?)?;
    let overlapping = docs
        .iter()
        .filter(|d| {
            model.root_evidence.contains_key(&d.id) || model.selection_documents.contains(&d.id)
        })
        .count();
    let mut budget = Budget::new(
        a.number("max-work", 500_000_000)?,
        a.number("max-seconds", 600.0)?,
    );
    let start = Instant::now();
    let e = train::evaluate(
        &model,
        &docs,
        &mut budget,
        a.values
            .get("budget")
            .map(|_| a.number("budget", 0))
            .transpose()?,
    )?;
    let report = json!({"bits_per_byte":e.bpb(),"evaluation":e,"seconds":start.elapsed().as_secs_f64(),
        "known_training_or_selection_documents":overlapping,"independent_by_exact_document_hash":overlapping==0,"process_usage":afrn_v5::resources::usage(),
        "note":"Exact-document overlap check only; no substring or near-duplicate audit."});
    println!("{}", serde_json::to_string_pretty(&report)?);
    if let Some(p) = a.path("report") {
        write_json(&p, &report)?;
    }
    Ok(())
}
fn run_infer(words: &[String]) -> Result<()> {
    let a = Args::parse(
        words,
        &[
            "model",
            "prompt",
            "prompt-file",
            "n",
            "temperature",
            "seed",
            "output",
            "budget",
            "max-data-bytes",
            "max-work",
            "max-seconds",
        ],
        &[],
    )?;
    if a.values.contains_key("prompt") && a.values.contains_key("prompt-file") {
        return Err("choose prompt or prompt-file".into());
    }
    if let Some(p) = a.path("output") {
        new_output(&p)?;
    }
    let model = model::load(Path::new(a.required("model")?))?;
    let cap = data_limit(&a)?;
    let prompt = if let Some(path) = a.path("prompt-file") {
        if fs::metadata(&path)?.len() > cap as u64 {
            return Err("prompt exceeds input cap".into());
        }
        fs::read(path)?
    } else {
        a.values
            .get("prompt")
            .map_or(vec![], |p| p.as_bytes().to_vec())
    };
    if prompt.len() > cap {
        return Err("prompt exceeds input cap".into());
    }
    let n = a.number("n", 200usize)?;
    let temperature = a.number("temperature", 0.85f64)?;
    if n > 1_000_000 || !temperature.is_finite() || temperature < 0.0 {
        return Err("invalid generation length/temperature".into());
    }
    let mut rng = Rng(a.number("seed", 42)?);
    let compiled = model.compile()?;
    let mut session = compiled.session();
    let mut budget = Budget::new(
        a.number("max-work", 500_000_000)?,
        a.number("max-seconds", 600.0)?,
    );
    let fuel = a
        .values
        .get("budget")
        .map(|_| a.number("budget", 0))
        .transpose()?;
    let mut charged = 0;
    for &b in &prompt {
        // Teacher-forced prompt processing executes the same scratch prediction
        // path as scoring, then commits only the real byte.
        session.distribution(fuel);
        session.observe(b);
        let work = session.counters().work;
        budget.spend(work - charged)?;
        charged = work;
    }
    let mut generated = Vec::with_capacity(n);
    for _ in 0..n {
        let p = session.distribution(fuel);
        let b = if temperature == 0.0 {
            (0..256)
                .max_by(|&a, &b| p[a].total_cmp(&p[b]).then(b.cmp(&a)))
                .unwrap() as u8
        } else {
            let logs = p.map(|p| p.ln() / temperature);
            let max = logs.iter().copied().fold(f64::NEG_INFINITY, f64::max);
            let weights = logs.map(|x| (x - max).exp());
            let mut x = rng.uniform() * weights.iter().sum::<f64>();
            let mut byte = 255;
            for (i, w) in weights.iter().enumerate() {
                x -= w;
                if x < 0.0 {
                    byte = i as u8;
                    break;
                }
            }
            byte
        };
        generated.push(b);
        session.observe(b);
        let work = session.counters().work;
        budget.spend(work - charged)?;
        charged = work;
    }
    if let Some(path) = a.path("output") {
        OpenOptions::new()
            .write(true)
            .create_new(true)
            .open(path)?
            .write_all(&generated)?;
    } else {
        let mut out = std::io::stdout().lock();
        out.write_all(&prompt)?;
        out.write_all(&generated)?;
        out.write_all(b"\n")?;
    }
    eprintln!(
        "{}",
        serde_json::to_string(
            &json!({"generated_bytes":n,"counters":session.counters(),"skipped_experts":session.skipped_experts})
        )?
    );
    Ok(())
}
fn run() -> Result<()> {
    let args: Vec<String> = std::env::args().skip(1).collect();
    if args.is_empty() || args.iter().any(|s| s == "--help" || s == "-h") {
        print!("{HELP}");
        return Ok(());
    }
    match args[0].as_str() {
        "train" => run_train(&args[1..]),
        "infer" => run_infer(&args[1..]),
        "eval" => run_eval(&args[1..]),
        "inspect" => {
            let a = Args::parse(&args[1..], &["model"], &[])?;
            let m = model::load(Path::new(a.required("model")?))?;
            println!(
                "{}",
                serde_json::to_string_pretty(
                    &json!({"version":m.version,"model_bytes":m.encoded_bytes()?,"training_documents":m.root_evidence.len(),
                "limits":m.limits,"stop_confidence":m.stop_confidence,"prediction_budget":m.prediction_budget,"modules":m.registry,
                "experts":m.experts.iter().map(|e|json!({"id":e.program.id(),"weight":e.weight,"program":e.program,"evidence_documents":e.evidence.len()})).collect::<Vec<_>>()})
                )?
            );
            Ok(())
        }
        _ => Err("unknown command; use --help".into()),
    }
}
fn main() {
    if let Err(e) = run() {
        eprintln!("error: {e}");
        std::process::exit(1);
    }
}
